name: React Doctor

on:
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  react-doctor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: millionco/react-doctor@main
        with:
          diff: main
